default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  username: whois
  password: whois

development:
  <<: *default
  database: registry_whois_development

test:
  <<: *default
  database: registry_whois_test

staging:
  <<: *default
  database: registry_whois_staging

production:
  <<: *default
  database: registry_whois_production
